Escape colon character

diff --git a/.github/workflows/test-for-translations.yml b/.github/workflows/test-for-translations.yml
--- a/.github/workflows/test-for-translations.yml
+++ b/.github/workflows/test-for-translations.yml
@@ -30,15 +30,17 @@ jobs:
     - name: Check for fuzzy translations
       id: fuzzy_translations
       continue-on-error: true
-      run: bash -c 'if [ $(cat backend/locale/en/LC_MESSAGES/django.po | grep "#, fuzzy" | wc -l) -gt 0 ];
+      run: bash -c 'if [ $(cat ./backend/locale/en/LC_MESSAGES/django.po | grep "#, fuzzy" | wc -l) -gt 0 ];
                     then echo "Unresolved fuzzy translations are present"; exit 1; fi'
 
     - name: Check for missing translations  
       id: missing_translations
       continue-on-error: true
       # https://stackoverflow.com/a/14799019/3342058
-      run: bash -c 'if [ $(awk '$NF == "msgstr \"\"" { c++ } END { print c ? c : "0" }' FS="\n" RS= ./backend/locale/en/LC_MESSAGES/django.po) -gt 0 ]; 
-                    then echo "Unresolved fuzzy translations are present"; exit 1; fi'
+      run: |
+        if [ $(awk '$NF == "msgstr \"\"" { c++ } END { print c ? c : "0" }' FS="\n" RS= ./backend/locale/en/LC_MESSAGES/django.po) -gt 0 ]; 
+          then echo "Missing translations are present"; exit 1; 
+        fi
 
     # Workaround because continue-on-error does not fail test
     - name: Return results
